import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./lib/styles/style.scss";
import "./lib/styles/css/bootstrap.min.css";
import ClientProvider from "@lib/services/ClientProvider";
import ErrorCatchService from "@lib/services/ErrorCatchService";
import AppModule from "./app.module";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Owlgram Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body dir="ltr" className={inter.className}>
        <ClientProvider>
          <AppModule>{children}</AppModule>
          {/* <ErrorCatchService>{children} </ErrorCatchService> */}
        </ClientProvider>
      </body>
    </html>
  );
}
